apiVersion: v1
kind: Service
metadata:
  name: insurance-claim-model-service
spec:
  selector:
    app: insurance-claim-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
